// Generated by scripts/resolve-pokeapi-ids.mjs.
// Maps a DB row id (regional/form variants only) to its own PokeAPI numeric
// pokemon id, so the static-artwork sprite fallback shows the correct
// form's art instead of the base species' (official-artwork is keyed by
// PokeAPI id, not national dex number, and form variants get their own id).
export const POKEAPI_ID_OVERRIDES: Record<number, number> = {
  1211: 10184, // Low Key Toxtricity
  // Legends Z-A batch:
  1163: 10276, // Terastal Terapagos
  1164: 10277, // Stellar Terapagos
  1165: 10278, // Mega Clefable
  1166: 10279, // Mega Victreebel
  1167: 10280, // Mega Starmie
  1168: 10282, // Mega Meganium
  1169: 10283, // Mega Feraligatr
  1170: 10284, // Mega Skarmory
  1171: 10285, // Mega Froslass
  1172: 10286, // Mega Emboar
  1173: 10288, // Mega Scolipede
  1174: 10289, // Mega Scrafty
  1175: 10290, // Mega Eelektross
  1176: 10291, // Mega Chandelure
  1177: 10292, // Mega Chesnaught
  1178: 10293, // Mega Delphox
  1179: 10295, // Mega Pyroar
  1180: 10296, // Mega Floette
  1181: 10297, // Mega Malamar
  1182: 10298, // Mega Barbaracle
  1183: 10299, // Mega Dragalge
  1184: 10300, // Mega Hawlucha
  1185: 10301, // Mega Zygarde
  1186: 10302, // Mega Drampa
  1187: 10303, // Mega Falinks
  1188: 10304, // Mega Raichu X
  1189: 10305, // Mega Raichu Y
  1190: 10306, // Mega Chimecho
  1191: 10307, // Mega Absol (Z-A)
  1192: 10308, // Mega Staraptor
  1193: 10309, // Mega Garchomp (Z-A)
  1194: 10310, // Mega Lucario (Z-A)
  1195: 10311, // Mega Heatran
  1196: 10312, // Mega Darkrai
  1197: 10313, // Mega Golurk
  1198: 10314, // Mega Meowstic Male
  1199: 10326, // Mega Meowstic Female
  1200: 10315, // Mega Crabominable
  1201: 10316, // Mega Golisopod
  1202: 10317, // Mega Magearna
  1203: 10318, // Mega Magearna (Original)
  1204: 10319, // Mega Zeraora
  1205: 10320, // Mega Scovillain
  1206: 10321, // Mega Glimmora
  1207: 10322, // Mega Tatsugiri (Curly)
  1208: 10323, // Mega Tatsugiri (Droopy)
  1209: 10324, // Mega Tatsugiri (Stretchy)
  1210: 10325, // Mega Baxcalibur

  // Origin/Mega batch 2:
  1155: 10245, // Origin Dialga
  1156: 10246, // Origin Palkia
  1157: 10007, // Origin Giratina
  1158: 10281, // Mega Dragonite
  1159: 10294, // Mega Greninja
  1160: 10273, // Wellspring Mask Ogerpon
  1161: 10274, // Hearthflame Mask Ogerpon
  1162: 10275, // Cornerstone Mask Ogerpon

  // Mechanical-form rows added alongside the sprite-slug overrides above:
  1116: 10008, // Heat Rotom
  1117: 10009, // Wash Rotom
  1118: 10010, // Frost Rotom
  1119: 10011, // Fan Rotom
  1120: 10012, // Mow Rotom
  1121: 10013, // Sunny Castform
  1122: 10014, // Rainy Castform
  1123: 10015, // Snowy Castform
  1124: 10022, // Black Kyurem
  1125: 10023, // White Kyurem
  1126: 10155, // Dusk Mane Necrozma
  1127: 10156, // Dawn Wings Necrozma
  1128: 10157, // Ultra Necrozma
  1129: 10086, // Unbound Hoopa
  1130: 10188, // Crowned Zacian
  1131: 10189, // Crowned Zamazenta
  1132: 10190, // Eternamax Eternatus
  1133: 10193, // Ice Rider Calyrex
  1134: 10194, // Shadow Rider Calyrex
  1135: 10272, // Bloodmoon Ursaluna
  1136: 10061, // Eternal Flower Floette
  1137: 10256, // Hero Palafin
  1066: 10033, // Mega Venusaur
  1067: 10036, // Mega Blastoise
  1068: 10090, // Mega Beedrill
  1069: 10073, // Mega Pidgeot
  1070: 10037, // Mega Alakazam
  1071: 10071, // Mega Slowbro
  1072: 10038, // Mega Gengar
  1073: 10039, // Mega Kangaskhan
  1074: 10040, // Mega Pinsir
  1075: 10041, // Mega Gyarados
  1076: 10042, // Mega Aerodactyl
  1077: 10045, // Mega Ampharos
  1078: 10072, // Mega Steelix
  1079: 10046, // Mega Scizor
  1080: 10047, // Mega Heracross
  1081: 10048, // Mega Houndoom
  1082: 10049, // Mega Tyranitar
  1083: 10065, // Mega Sceptile
  1084: 10050, // Mega Blaziken
  1085: 10064, // Mega Swampert
  1086: 10051, // Mega Gardevoir
  1087: 10066, // Mega Sableye
  1088: 10052, // Mega Mawile
  1089: 10053, // Mega Aggron
  1090: 10054, // Mega Medicham
  1091: 10055, // Mega Manectric
  1092: 10070, // Mega Sharpedo
  1093: 10087, // Mega Camerupt
  1094: 10067, // Mega Altaria
  1095: 10056, // Mega Banette
  1096: 10057, // Mega Absol
  1097: 10074, // Mega Glalie
  1098: 10089, // Mega Salamence
  1099: 10076, // Mega Metagross
  1100: 10062, // Mega Latias
  1101: 10063, // Mega Latios
  1102: 10079, // Mega Rayquaza
  1103: 10088, // Mega Lopunny
  1104: 10058, // Mega Garchomp
  1105: 10059, // Mega Lucario
  1106: 10060, // Mega Abomasnow
  1107: 10068, // Mega Gallade
  1108: 10069, // Mega Audino
  1109: 10075, // Mega Diancie
  1110: 10034, // Mega Charizard X
  1111: 10035, // Mega Charizard Y
  1112: 10043, // Mega Mewtwo X
  1113: 10044, // Mega Mewtwo Y
  1114: 10077, // Primal Kyogre
  1115: 10078, // Primal Groudon

  "19": 10091,
  "21": 10092,
  "28": 10100,
  "30": 10101,
  "32": 10102,
  "42": 10103,
  "44": 10104,
  "57": 10105,
  "59": 10106,
  "61": 10107,
  "62": 10161,
  "64": 10108,
  "71": 10229,
  "73": 10230,
  "88": 10109,
  "90": 10110,
  "92": 10111,
  "94": 10162,
  "96": 10163,
  "98": 10164,
  "100": 10165,
  "105": 10166,
  "110": 10112,
  "112": 10113,
  "124": 10231,
  "127": 10232,
  "129": 10114,
  "132": 10115,
  "138": 10167,
  "151": 10168,
  "158": 10252,
  "159": 10251,
  "160": 10250,
  "178": 10169,
  "179": 10170,
  "181": 10171,
  "193": 10233,
  "231": 10253,
  "237": 10172,
  "250": 10234,
  "255": 10235,
  "264": 10173,
  "305": 10174,
  "307": 10175,
  "547": 10236,
  "594": 10237,
  "601": 10176,
  "603": 10177,
  "610": 10179,
  "619": 10238,
  "621": 10239,
  "669": 10180,
  "681": 10240,
  "758": 10241,
  "761": 10242,
  "769": 10243,
  "781": 10244
};
